name: setup-bun
description: "Setup Bun ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧"
runs:
  using: "composite"
  steps:
    - name: Setup Bun ⚙️
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.14

    # - name: Cache dependencies ⚡
    #   id: cache_dependencies
    #   uses: actions/cache@v3
    #   with:
    #     path: |
    #       ~/.bun
    #       node_modules
    #     key: bun-deps-${{ hashFiles('bun.lockb') }}

    - name: Install dependencies 🔧
      shell: bash
      run: bun install --frozen-lockfile
